README.md
=> README.md addition

fakemod/fakemod.py
=> Change to local timezone not UTC

randomnoa/randomnoa.py
=> fix randnoa

README.md
=> Test for readme before pushing to main

randomnoa/randomnoa.py
=> [RandomNoa] Replying to unknown message

randomnoa/cards.json, randomnoa/randomnoa.py
Adds the new Love Injection card, from the current event on the JP server.
=> [RandomNoa] Update cards list, and random images

randomnoa/cards.json, randomnoa/randomnoa.py
=> NEW CARDS!

ownermanagement/ownermanagement.py
=> SECURITY UPDATE

breadfact/breadfact.py
- Changed int, so it won't overflow.
Closes #29.
=> [BreadFact] Index list out of range 

breadfact/breadfact.py
=> [BreadFact] Disable reply pings

randomnoa/randomnoa.py
=> [RandomNoa] Handle reply exception 

randomnoa/cards.json, randomnoa/randomnoa.py
- A new D4DJ Groovy Mix card has been added here, "I can see through your escape route". 
- This card is new, and is not available in the JP server yet. 
- Do not merge this pull request until the event in the JP server has started.
=> [RandomNoa] Addition of new Noa Fukushima card

randomnoa/cards.json
Fixes a wrong "field name" to the correct one.
Closes #41
=> [RandomNoa] Fix keyerror (again)

fakemod/fakemod.py, ownermanagement/ownermanagement.py
- in [ownermanagement/ownermanagement.py](https://github.com/Noa-Discordbot/Noa-cogs/ownermanagement/ownermanagement.py) removed unused imports
- in [fakemod/fakemod.py](https://github.com/Noa-DiscordBot/Noa-cogs/fakemod/fakemod.py) removed case which is unused.
=> LGTM.com bot "recommended" changes

README.md, russianroulette/__init__.py, russianroulette/info.json, russianroulette/russianroulette.py
Adds the RussianRoulette cog to this repository. This cog is unfinished, but eh, who cares.
Yes, it should work.
=> Initialization of RussianRoulette Cog

breadfact/breadfact.py, fakemod/fakemod.py, ownermanagement/ownermanagement.py, randomnoa/randomnoa.py, russianroulette/russianroulette.py
Ok Jeff :D
Does style reformatting really need to be tested? Didn't think so. Anyways... here you go Jeff
=> Here's help with black and isort

.github/workflows/style-reformatting.yml
=> funny number pr

randomnoa/data/cards.json
Adds the (not-so) new Noa card into the RandomNoa cards list.
Closes #73 
Yes
(note to self: do not delete this branch :), thanks)
=> [RandomNoa] New card

russianroulette/russianroulette.py
This PR allows us to change russianroulette messages.
Alongside with the above, a few ~~stuffyouwontnoticewhenusingthecog~~ internal stuff are changed to make the cog more efficient
Yes
=> [RussianRoulette] Add the command to do customizable messages

README.md, randomnoa/data/cards.json, randomnoa/randomnoa.py
Adds a new card (カワイイに捧ぐ三宝)
Closes #75 
Includes version bump, too.
Yes
=> [RandomNoa] Newwwwww card

.github/ISSUE_TEMPLATE/buggies.yml, .github/ISSUE_TEMPLATE/featurereq.yml
=> [Repo] Removal of discord user information field

.github/CODEOWNERS, README.md, fakemod/fakemod.py, randomnoa/data/cards.json, randomnoa/randomnoa.py
Its wings are too small to get its fat little body off the ground.
The bee, of course, flies anyway because bees don't care what humans think is impossible.
Yellow, black. Yellow, black. Yellow, black. Yellow, black.
Ooh, black and yellow!
Let's shake it up a little.
Barry! Breakfast is ready!
Coming!
Hang on a second.
Hello?
Barry?
Adam?
Can you believe this is happening?
I can't.
I'll pick you up.
Looking sharp.
Use the stairs, Your father paid good money for those.
Sorry. I'm excited.
Here's the graduate.
We're very proud of you, son.
A perfect report card, all B's.
Very proud.
Ma! I got a thing going here.
You got lint on your fuzz.
Ow! That's me!
Wave to us! We'll be in row 118,000.
Bye!
Barry, I told you, stop flying in the house!
Hey, Adam.
Hey, Barry.
Is that fuzz gel?
A little. …
=> According to all known laws of aviation, there is no way a bee should be able to fly.

randomnoa/data/cards.json
Changes imgbb host to bae.lena,moe
yes
=> [Randomnoa] New host

randomnoa/randomnoa.py
Footer stuff
- [ X ] Bug Fix
||Ogey||
||rrat||
=> [RandomNoa] Credits for bae.lena.moe (New host!)

README.md, randomnoa/data/cards.json, randomnoa/randomnoa.py
This PR includes everything for RandomNoa v2. Refer #80 for more information.
No, WIP.
=> [RandomNoa] Version 2

README.md
I recently made one of the letters in my discord username capital, so just wanted to update it here.
No... Its the readme
=> Update My Discord Username

.github/workflows/style-checks.yml, breadfact/breadfact.py, ownermanagement/ownermanagement.py, randomnoa/randomnoa.py, russianroulette/russianroulette.py
Just shortens the code by moving some stuff to init and some stuff to another function.
No, I don't do red so I can't...
=> Shorten the code
